spring:
  application:
    name: solstice

  datasource:
    url: jdbc:postgresql://localhost:5433/solstice_db
    username: solstice_user
    password: solstice_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/solstice_db

    redis:
      host: localhost
      port: 6379

server:
  port: 8080
